version: '3.3'
services:
    iobroker:
        image: 'buanet/iobroker:${IOBROKER_VERSION}'
        restart: always
        hostname: ${IOBROKER_HOSTNAME}
        container_name: iobroker
        network_mode: "host"
        environment:
            - USBDEVICES=
            - TZ=Europe/Berlin
            - ZWAVE=false
            - AVAHI=false
            - IOB_STATESDB_TYPE=jsonl
            - IOB_STATESDB_PORT=9000
            - IOB_STATESDB_HOST=0.0.0.0
            - IOB_OBJECTSDB_TYPE=jsonl
            - IOB_OBJECTSDB_PORT=9001
            - IOB_OBJECTSDB_HOST=0.0.0.0
            - IOB_STATESDB_PASS= #leave this empty
            - IOB_MULTIHOST=master
            - IOB_ADMINPORT=8081
            - SETGID=1000
            - SETUID=1000
        volumes:
            - '${IOBROKER_PATH}:/opt/iobroker:rw'


    redis:
        image: 'bitnami/redis:latest'
        hostname: redis
        container_name: iobroker-redis
        network_mode: "host"       
        restart: unless-stopped
        user: '1000'  
        volumes:
            - '${IOBROKER_REDIS_PATH}:/bitnami:rw'
        environment:
            - REDIS_IO_THREADS_DO_READS=yes
            - REDIS_IO_THREADS=4
            - REDIS_PASSWORD= #leave this empty
            - ALLOW_EMPTY_PASSWORD=yes