version: "3.9"
services:
  bitwarden:
    container_name: bitwarden
    image: vaultwarden/server:latest
    hostname: ${HOSTNAME}
    restart: unless-stopped
    ports:
      - 180:80
    environment:
      - ADMIN_TOKEN=${BITWARDEN_ADMIN_TOKEN}
    env_file:
      - ".env"
    volumes:
      - '${BITWARDEN_DATA}:/data:rw'
